SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `dcs` DEFAULT CHARACTER SET latin1 ;
USE `dcs` ;

-- -----------------------------------------------------
-- Table `dcs`.`TB_PROPERTIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dcs`.`TB_PROPERTIES` ;

CREATE  TABLE IF NOT EXISTS `dcs`.`TB_PROPERTIES` (
  `prop.key` VARCHAR(64) NOT NULL ,
  `prop.value` VARCHAR(256) NOT NULL ,
  PRIMARY KEY (`prop.key`) ,
  UNIQUE INDEX `key_UNIQUE` (`prop.key` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dcs`.`SITE_CONFIGURATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dcs`.`SITE_CONFIGURATION` ;

CREATE  TABLE IF NOT EXISTS `dcs`.`SITE_CONFIGURATION` (
  `SITE_ID` INT NOT NULL ,
  `SITE_NAME` VARCHAR(100) NULL ,
  PRIMARY KEY (`SITE_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcs`.`SHIFT_MODEL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dcs`.`SHIFT_MODEL` ;

CREATE  TABLE IF NOT EXISTS `dcs`.`SHIFT_MODEL` (
  `SHIFT_MODEL_ID` INT NOT NULL ,
  `SHIFT_MODEL_NAME` VARCHAR(100) NULL ,
  PRIMARY KEY (`SHIFT_MODEL_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcs`.`MACHINE_CLASS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dcs`.`MACHINE_CLASS` ;

CREATE  TABLE IF NOT EXISTS `dcs`.`MACHINE_CLASS` (
  `MACHINE_CLASS_ID` INT NOT NULL ,
  `MACHINE_CLASS_NAME` VARCHAR(100) NULL ,
  PRIMARY KEY (`MACHINE_CLASS_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcs`.`MACHINE_CONFIGURATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dcs`.`MACHINE_CONFIGURATION` ;

CREATE  TABLE IF NOT EXISTS `dcs`.`MACHINE_CONFIGURATION` (
  `MACHINE_ID` INT NOT NULL ,
  `MACHINE_NAME` VARCHAR(100) NULL ,
  `MACHINE_DESCRIPTION` TEXT NULL ,
  `SITE_ID` INT NULL ,
  `SHIFT_MODEL_ID` INT NULL ,
  `MACHINE_CLASS_ID` INT NOT NULL ,
  PRIMARY KEY (`MACHINE_ID`) ,
  INDEX `fk_MACHINE_CONFIGURATION_SITE_CONFIGURATION` (`SITE_ID` ASC) ,
  INDEX `fk_MACHINE_CONFIGURATION_SHIFT_MODEL1` (`SHIFT_MODEL_ID` ASC) ,
  INDEX `fk_MACHINE_CONFIGURATION_MACHINE_CLASS1` (`MACHINE_CLASS_ID` ASC) ,
  CONSTRAINT `fk_MACHINE_CONFIGURATION_SITE_CONFIGURATION`
    FOREIGN KEY (`SITE_ID` )
    REFERENCES `dcs`.`SITE_CONFIGURATION` (`SITE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MACHINE_CONFIGURATION_SHIFT_MODEL1`
    FOREIGN KEY (`SHIFT_MODEL_ID` )
    REFERENCES `dcs`.`SHIFT_MODEL` (`SHIFT_MODEL_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MACHINE_CONFIGURATION_MACHINE_CLASS1`
    FOREIGN KEY (`MACHINE_CLASS_ID` )
    REFERENCES `dcs`.`MACHINE_CLASS` (`MACHINE_CLASS_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcs`.`SHIFT_CONFIGURATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dcs`.`SHIFT_CONFIGURATION` ;

CREATE  TABLE IF NOT EXISTS `dcs`.`SHIFT_CONFIGURATION` (
  `SHIFT_ID` INT NOT NULL ,
  `SHIFT_NAME` VARCHAR(100) NULL ,
  `SHIFT_START` INT NULL ,
  `SHIFT_LENGHT` INT NULL ,
  `SHIFT_MODEL_ID` INT NOT NULL ,
  PRIMARY KEY (`SHIFT_ID`) ,
  INDEX `fk_SHIFT_CONFIGURATION_SHIFT_MODEL1` (`SHIFT_MODEL_ID` ASC) ,
  CONSTRAINT `fk_SHIFT_CONFIGURATION_SHIFT_MODEL1`
    FOREIGN KEY (`SHIFT_MODEL_ID` )
    REFERENCES `dcs`.`SHIFT_MODEL` (`SHIFT_MODEL_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcs`.`MACHINE_STATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dcs`.`MACHINE_STATE` ;

CREATE  TABLE IF NOT EXISTS `dcs`.`MACHINE_STATE` (
  `MACHINE_STATE_ID` INT NOT NULL ,
  `MACHINE_ID` INT NOT NULL ,
  `STATE_CREATION_DATE` DATETIME NOT NULL ,
  `MACHINE_STATE` INT NULL ,
  `MACHINE_SPEED` INT NULL ,
  PRIMARY KEY (`MACHINE_STATE_ID`) ,
  INDEX `fk_MACHINE_STATE_MACHINE_CONFIGURATION1` (`MACHINE_ID` ASC) ,
  UNIQUE INDEX `STATE_PER_MACHINE_AND_DATE` (`MACHINE_ID` ASC, `STATE_CREATION_DATE` ASC, `MACHINE_STATE_ID` ASC) ,
  CONSTRAINT `fk_MACHINE_STATE_MACHINE_CONFIGURATION1`
    FOREIGN KEY (`MACHINE_ID` )
    REFERENCES `dcs`.`MACHINE_CONFIGURATION` (`MACHINE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcs`.`SHIFT_RESULT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dcs`.`SHIFT_RESULT` ;

CREATE  TABLE IF NOT EXISTS `dcs`.`SHIFT_RESULT` (
  `SHIFT_RESULT_ID` INT NOT NULL ,
  `SHIFT_RESULT_DATE` DATETIME NOT NULL ,
  `MACHINE_ID` INT NOT NULL ,
  `SHIFT_ID` INT NOT NULL ,
  `COUNTER_IN` INT NULL ,
  `COUNTER_OUT` INT NULL ,
  `TIME_RUN` INT NULL ,
  PRIMARY KEY (`SHIFT_RESULT_ID`) ,
  INDEX `fk_SHIFT_RESULT_MACHINE_CONFIGURATION1` (`MACHINE_ID` ASC) ,
  INDEX `fk_SHIFT_RESULT_SHIFT_CONFIGURATION1` (`SHIFT_ID` ASC) ,
  UNIQUE INDEX `SHIFT_RESULT_PER_DATE` (`MACHINE_ID` ASC, `SHIFT_RESULT_DATE` ASC, `SHIFT_ID` ASC) ,
  CONSTRAINT `fk_SHIFT_RESULT_MACHINE_CONFIGURATION1`
    FOREIGN KEY (`MACHINE_ID` )
    REFERENCES `dcs`.`MACHINE_CONFIGURATION` (`MACHINE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SHIFT_RESULT_SHIFT_CONFIGURATION1`
    FOREIGN KEY (`SHIFT_ID` )
    REFERENCES `dcs`.`SHIFT_CONFIGURATION` (`SHIFT_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
